id = "flutter"
name = "Dart & Flutter"
version = "0.1.0"
schema_version = 1
authors = ["Zed Flutter Plugin Team"]
description = "Dart and Flutter development support."
repository = "https://github.com/iakii/zed-flutter-plugin"

[language_servers.dart]
name = "Dart LSP"
language = "Dart"
languages = ["Dart"]

[grammars.dart]
repository = "https://github.com/UserNobody14/tree-sitter-dart"
commit = "6922ad29141e819773d6ffb0c6d2c27adefb5acc"

[debug_adapters.flutter]
schema = "debug_adapter_schemas/flutter.json"
